--1)test veritabanýnýzda employee isimli sütun bilgileri id(INTEGER), name VARCHAR(50), birthday DATE, email VARCHAR(100) olan bir tablo oluþturalým.
	    CREATE TABLE employee(id integer, name varchar(50),birthday date, email varchar(100));
--2)Oluþturduðumuz employee tablosuna 'Mockaroo' servisini kullanarak 50 adet veri ekleyelim.sýralayýnýz.
        insert into MOCK_DATA (id, name, email, birhtday) values (1, 'Nelia', 'nruoss0@foxnews.com', '10/12/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (2, 'Cordy', 'cwurst1@reuters.com', '6/16/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (3, 'Marlin', 'mmoneypenny2@blogger.com', '9/12/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (4, 'Zed', 'zhubbucke3@patch.com', '12/15/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (5, 'Pamelina', 'pmolder4@bluehost.com', '9/28/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (6, 'Neal', 'nmelwall5@fema.gov', '12/19/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (7, 'Farrell', 'fbessom6@census.gov', '2/14/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (8, 'Jilleen', 'jranby7@youku.com', '1/4/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (9, 'Norby', 'nanmore8@spiegel.de', '1/28/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (10, 'Byrle', 'blevinge9@over-blog.com', '4/4/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (11, 'Ramsey', 'rshellsheara@constantcontact.com', '7/15/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (12, 'Eilis', 'edevigneb@flickr.com', '7/16/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (13, 'Isaiah', 'ibingec@example.com', '10/31/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (14, 'Philis', 'pazemard@sciencedaily.com', '3/29/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (15, 'Katrinka', 'klinne@dell.com', '9/8/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (16, 'Adrea', 'arussf@zdnet.com', '7/16/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (17, 'Dionne', 'dcornug@whitehouse.gov', '8/11/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (18, 'Gwennie', 'gconrarth@reddit.com', '4/27/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (19, 'Mufinella', 'mmougini@un.org', '1/26/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (20, 'Adele', 'atruranj@ebay.co.uk', '8/12/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (21, 'Robinett', 'rfullomk@i2i.jp', '3/5/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (22, 'Toby', 'tmacdowall@imageshack.us', '6/25/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (23, 'Masha', 'mdelvem@bbc.co.uk', '10/31/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (24, 'Felike', 'fjoanicn@skype.com', '6/16/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (25, 'Ilario', 'ifarriero@chicagotribune.com', '10/29/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (26, 'Adriano', 'agossep@netlog.com', '9/7/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (27, 'Hailey', 'htabourinq@accuweather.com', '7/5/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (28, 'Yurik', 'ybirdr@nytimes.com', '3/11/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (29, 'Brennen', 'bhammerichs@dedecms.com', '6/11/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (30, 'Gordie', 'ghanburryt@senate.gov', '1/1/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (31, 'Ferdinanda', 'fberniu@naver.com', '11/15/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (32, 'Fowler', 'fcluattv@miitbeian.gov.cn', '11/10/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (33, 'Hewe', 'hforlongew@qq.com', '8/7/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (34, 'Urban', 'ufrickx@prlog.org', '6/3/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (35, 'Hayward', 'hjodrellecy@eepurl.com', '10/31/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (36, 'Melany', 'mranshawz@slashdot.org', '2/18/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (37, 'Otho', 'ocorris10@nps.gov', '2/27/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (38, 'Brucie', 'btoderi11@nationalgeographic.com', '12/23/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (39, 'Patrizia', 'pcone12@utexas.edu', '11/28/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (40, 'Pavla', 'pkerman13@tumblr.com', '5/7/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (41, 'Juliet', 'jfieldsend14@jigsy.com', '3/25/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (42, 'Rozamond', 'rcolnet15@hubpages.com', '7/21/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (43, 'Bat', 'btidswell16@elpais.com', '3/29/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (44, 'Leonidas', 'ldow17@privacy.gov.au', '8/6/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (45, 'Murdoch', 'maberhart18@si.edu', '1/20/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (46, 'Jarad', 'jwibrow19@imageshack.us', '6/27/2024');
insert into MOCK_DATA (id, name, email, birhtday) values (47, 'Micki', 'mthomel1a@reddit.com', '8/24/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (48, 'Berrie', 'bmion1b@hatena.ne.jp', '12/1/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (49, 'Arron', 'acossum1c@printfriendly.com', '9/21/2023');
insert into MOCK_DATA (id, name, email, birhtday) values (50, 'Isabeau', 'iwhitecross1d@ebay.com', '1/15/2024');
--3)Sütunlarýn her birine göre diðer sütunlarý güncelleyecek 5 adet UPDATE iþlemi yapalým.
        UPDATE employee SET name='Melisa' WHERE id=30;
		UPDATE employee SET birthday= '8/15/2024' where id=50;
		UPDATE employee SET email= 'bm1b@hatena.ne.jp' where email='bmion1b@hatena.ne.jp';
		UPDATE employee SET name='Micki' WHERE id=8;
		UPDATE employee SET email= 'bb@hatena.ne.jp' WHERE id=8;
--4)Sütunlarýn her birine göre ilgili satýrý silecek 5 adet DELETE iþlemi yapalým.
        DELETE employee where id=40;
		DELETE employee where name='Otho';
		DELETE employee where email='pcone12@utexas.edu';
		DELETE employee where birthday='11/28/2023' ;
		DELETE employee where id IN(2,8,16);